server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/recycle?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
  redis:
    database: 1
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 3000
        min-idle: 2
    port: 6379
    timeout: 5000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  #时间戳统一转换为指定格式
    time-zone: GMT+8  # 时区修改为东8区
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath:mapper/**/*Mapper.xml
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
coisini:
  security:
    jwt-key: recycle-admin
    # 过期时间
    token-expired-in: 86400000
