server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/recycle?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
  redis:
    database: 1
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 3000
        min-idle: 2
    port: 6379
    timeout: 5000
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml,classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      table-prefix: recycle_
  configuration-properties:
    prefix: recycle_
wechat:
  appid: xxxxxxxxxxxxxxx
  appsecret: xxxxxxxxxxxxxxx
coisini:
  security:
    jwt-key: recycle
    # 过期时间
    token-expired-in: 86400000